name: project
recipe: laravel
config:
  webroot: public
proxy:
  mailhog:
    - mail.project.test
services:
  node:
    type: node:12
    build:
      - npm install
  phpmyadmin:
    type: phpmyadmin
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
tooling:
  npm:
    service: node
  node:
    service: node
  phpunit:
    service: appserver
    description: "Run PHP Unit tests: lando phpunit"
    cmd: /app/vendor/bin/phpunit
